
### Get All Producers
GET http://localhost:8082/api/producers
### Get All Engines
GET http://localhost:8082/api/engines
### 
GET http://localhost:8082/api/producers/Bmw
### 
GET http://localhost:8082/api/engines/1
### 
GET http://localhost:8080/api/producers/Audi/engines
### Post New Producer With Given Details 
POST http://localhost:8082/api/producers
Content-Type: application/json

{
    "name":"Bmw",
    "nip":123
}
### Add Engine
POST http://localhost:8082/api/producers/Bmw/engines/
Content-Type: application/json

{
    "name":"M52B28",
    "capacity": 2798,
    "yearz": 2005,
    "producer":"Bmw"
}
### Edit Engine
PUT http://localhost:8082/api/producers/Bmw/engines/4
Content-Type: application/json

{
    "name":"2.0 Turbo (New)",
    "capacity": 1998,
    "yearz": 1998,
    "producer":"Bmw"
}
### Delete Engine
DELETE http://localhost:8082/api/producers/Bmw/engines/4
### Delete Producer By Given Name
DELETE http://localhost:8082/api/producers/Bmw
### Put Producer
PUT http://localhost:8082/api/producers/Audi
Content-Type: application/json

{
    "nip": 123456,
    "yearz": 2022
}
